In [1]:
import pandas as pd

bb_music = pd.read_csv("billboard.csv")
bb_music

,artiste,track,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,x5th.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Madonna,Music,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,98,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,99,99.0,99.0,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,99,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
bb_music.shape

(317, 81)

In [3]:
bb_music.dtypes

artiste          object
track            object
genre            object
date.entered     object
date.peaked      object
                 ...
x72nd.week      float64
x73rd.week      float64
x74th.week      float64
x75th.week      float64
x76th.week      float64
Length: 81, dtype: object

In [4]:
bb_music['date.entered'] = pd.to_datetime(bb_music['date.entered'])

In [5]:
bb_music['date.peaked'] = pd.to_datetime(bb_music['date.peaked'])

In [6]:
bb_music

,artiste,track,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,x5th.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Madonna,Music,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,98,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,99,99.0,99.0,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,99,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
bb_music = pd.melt(bb_music, id_vars=['artiste', 'track', 'genre', 'date.entered', 'date.peaked'], var_name='week', value_name='rank')

In [8]:
bb_music

,artiste,track,genre,date.entered,date.peaked,week,rank
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,x1st.week,78.0
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,x1st.week,15.0
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,x1st.week,71.0
3,Madonna,Music,Rock,2000-08-12,2000-09-16,x1st.week,41.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,x1st.week,57.0
...,...,...,...,...,...,...,...
24087,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,x76th.week,NaN
24088,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,x76th.week,NaN
24089,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,x76th.week,NaN
24090,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,x76th.week,NaN
24091,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,x76th.week,NaN

In [9]:
bb_music['week'] = bb_music['week'].str.extract('(\d+)').astype(int)

In [10]:
bb_music

,artiste,track,genre,date.entered,date.peaked,week,rank
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,1,78.0
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,1,15.0
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,1,71.0
3,Madonna,Music,Rock,2000-08-12,2000-09-16,1,41.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,1,57.0
...,...,...,...,...,...,...,...
24087,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,76,NaN
24088,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,76,NaN
24089,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,76,NaN
24090,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,76,NaN
24091,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,76,NaN

In [12]:
#inserting a new column in data frame (entered_to_peak) = date.peaked - date.entered
bb_music.insert(5, "entered_to_peak", (bb_music['date.peaked']-bb_music['date.entered']) )

In [13]:
bb_music

,artiste,track,genre,date.entered,date.peaked,entered_to_peak,week,rank
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,56 days,1,78.0
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,56 days,1,15.0
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,98 days,1,71.0
3,Madonna,Music,Rock,2000-08-12,2000-09-16,35 days,1,41.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,70 days,1,57.0
...,...,...,...,...,...,...,...,...
24087,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,0 days,76,NaN
24088,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,0 days,76,NaN
24089,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,0 days,76,NaN
24090,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,0 days,76,NaN
24091,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,0 days,76,NaN

In [15]:
bb_music.sort_values(['entered_to_peak', 'rank'], ascending=[False,False])

,artiste,track,genre,date.entered,date.peaked,entered_to_peak,week,rank
46,Creed,Higher,Rock,1999-09-11,2000-07-22,315 days,1,81.0
363,Creed,Higher,Rock,1999-09-11,2000-07-22,315 days,2,77.0
680,Creed,Higher,Rock,1999-09-11,2000-07-22,315 days,3,73.0
997,Creed,Higher,Rock,1999-09-11,2000-07-22,315 days,4,63.0
1314,Creed,Higher,Rock,1999-09-11,2000-07-22,315 days,5,61.0
...,...,...,...,...,...,...,...,...
24087,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,0 days,76,NaN
24088,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,0 days,76,NaN
24089,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,0 days,76,NaN
24090,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,0 days,76,NaN
24091,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,0 days,76,NaN

In [ ]:
# After 35 days Artiste: Creed, song: 'Higher' ranked number 1